spring.application.name=fintrack-backend

spring.datasource.url=jdbc:mysql://localhost:3306/fintrack_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=fintrack_user
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


